FROM node:latest

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app


COPY ./ /usr/src/app
#COPY package.json /usr/src/app
#RUN cd /usr/src/app;

RUN cd /usr/src/app


EXPOSE 8090

ENTRYPOINT npm run server