FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD root
ENV MYSQL_DATABASE wikipet
ENV MYSQL_USER admin
ENV MYSQL_PASSWORD admin

COPY ./database /usr/src/database

RUN sleep 10 && \
    mysql -uadmin -padmin wikipet < /usr/src/database/wikipet.sql