version: '3'
services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"
  web:
    build:
      context: ./
      dockerfile: Dockerfile.node
    ports:
      - "8090:8090"
    volumes:
      - .:/usr/src/volume
    links:
    - db:db